ip: 0.0.0.0
httpPort: ${httpPort:8080}
enableHttp: ${enableHttp:true}
enableHttp2: true
httpsPort: ${httpsPort:8443}
enableHttps: ${enableHttps:false}
keystoreName: server.keystore
serviceId: com.xlongwei.light4j
enableRegistry: ${enableRegistry:false}
dynamicPort: ${dynamicPort:false}
minPort: ${minPort:12400}
maxPort: ${maxPort:12500}
workerThreads: ${workerThreads:18}
alwaysSetDate: false
